name: deploy

on:
    schedule:
        # - cron: "0 19 * * *"

jobs:
    cron:
        runs-on: ubuntu-18.04

        strategy:
            matrix:
                node-version: [12.x,14.x,16.x]

        steps:
            - uses: actions/checkout@v2
               
              - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Run scripts in server
              uses: appleboy/ssh-action@master
              with:
                  key: ${{ secrets.SSH_KEY }}
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  script: |
                      cd seuchida_BE
                      sudo -s
                      # git reset --hard origin/master
                      # git fetch
                      git pull
                      npm install
                      sudo pm2 restart all
