# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
    branches:
    - master
    - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source cod
      uses: actions/checkout@v2

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x' # node 12.x 버전 사용

    - name: Installing NPM
      run: npm install

    - name: Building application
      run: npm run build


    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp build/libs/*.jar deploy/application.jar
        cp Procfile deploy/Procfile
        cp -r .ebextensions deploy/.ebextensions
        cp -r .platform deploy/.platform
        cd deploy && zip -r deploy.zip .
        
    - name: Beanstalk Deploy for app
      uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
        application_name: Test-01
        environment_name: Test01-env-1
        region: ap-northeast-2
        deployment_package: deploy/seuchida_BE_CICD.zip
        version_label: "my-app-${{ steps.format-time.outputs.replaced }}"

    - name: Deployed!
      run: echo App deployed to ELB
