# This is a basic workflow to help you get started with Actions

name: CICD
env:
  EB_PACKAGE_S3_BUCKET_NAME: "elasticbeanstalk-ap-northeast-2-047988302194"
  EB_APPLICATION_NAME: "Test-01"
  EB_ENVIRONMENT_NAME: "Test01-env-1"
  DEPLOY_PACKAGE_NAME: "deploy.zip"
  AWS_REGION_NAME: "ap-northeast-2"

on:
  push:
    branches:
    - master
    - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source cod
      uses: actions/checkout@v2

    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x' # node 12.x 버전 사용

    - name: Installing NPM
      run: npm install

    - name: Building application
      run: npm run build

    - name: Generate deployment package
			# 패키지를 deploy.zip 으로 압축
      run: zip -r deploy.zip . -x "**node_modules**" "package-lock.json" ".git**"
    
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
    
    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "$"
        replace-with: "-"
        flags: "g"
        
    - name: Beanstalk Deploy for app
      uses: einaregilsson/beanstalk-deploy@v9
      with:
				# github aws access key
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
				# github aws secret key
        aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
				# Elastic beanstalk application 이름
        application_name: Test-01
				# Elasticbeanstalk env 이름
        environment_name: Test01-env-1
				# aws 리전
        region: ap-northeast-2
				# 배포 할 패키지
        deployment_package: deploy.zip
				# 버전 레이블
        version_label: "my-app-${{ steps.format-time.outputs.replaced }}"

		# 모든 액션 이 완료되고, 화면에 출력 할 내용
    - name: Deployed!
      run: echo App deployed to ELB
 
 #fail 로그 하는 부분
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      
  # 초안 참고: https://www.notion.so/Github-action-Nodejs-ELB-8643f007d55540199359ce210ca19288
